POST http://localhost:80/books HTTP/1.1
Content-Type: application/json

{
    "title": "A brief history of time",
    "author": "640720df8b1fc552d84cf3bb",
    "publisher": "640728575a54f6ea107a7e8f",
    "pages": 256
}