PUT http://localhost:80/books/6404864fef621117ac2cd555 HTTP/1.1
Content-Type: application/json

{
    "title": "The Hitchhiker's Guide to the Galaxy",
    "author": "640720b88b1fc552d84cf3b8",
    "publisher": "Pan Books",
    "pages": 224
}